Repository TryAtSoftware/Extensions, pull requests merged in 2023-07, with the labels that each got.

#48 Load referenced assemblies
  TryAtSoftware.Extensions.Reflection.Tests/AssemblyExtensionsTests.cs
  TryAtSoftware.Extensions.Reflection.Tests/Options/LoadReferencedAssembliesOptionsTests.cs
  TryAtSoftware.Extensions.Reflection.Tests/TryAtSoftware.Extensions.Reflection.Tests.csproj
  TryAtSoftware.Extensions.Reflection/AssemblyExtensions.cs
  TryAtSoftware.Extensions.Reflection/AssemblyLoader.cs
  TryAtSoftware.Extensions.Reflection/Interfaces/IAssemblyLoader.cs
  TryAtSoftware.Extensions.Reflection/Options/LoadReferencedAssembliesOptions.cs
Labels: feature

#51 Housekeeping
  TryAtSoftware.Extensions.Collections.Tests/TryAtSoftware.Extensions.Collections.Tests.csproj
  TryAtSoftware.Extensions.Collections.md
  TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
  TryAtSoftware.Extensions.Reflection.Tests/Randomization/AgeRandomizer.cs
  TryAtSoftware.Extensions.Reflection.Tests/Randomization/PersonRandomizer.cs
  TryAtSoftware.Extensions.Reflection.Tests/Randomization/StudentRandomizer.cs
  TryAtSoftware.Extensions.Reflection.Tests/TryAtSoftware.Extensions.Reflection.Tests.csproj
  TryAtSoftware.Extensions.Reflection.md
  TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
Labels: documentation, enhancement

#52 Added documentation for the new assembly extensions
  TryAtSoftware.Extensions.Reflection.md
  TryAtSoftware.Extensions.Reflection/AssemblyExtensions.cs
  TryAtSoftware.Extensions.Reflection/Options/LoadReferencedAssembliesOptions.cs
Labels: documentation

#53 Increased the `TryAtSoftware.Extensions.Reflection` package version to 1.1.2-alpha.1
  TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
Labels: release

#55 Made improvements to the `Core validation` CI pipeline
  .github/workflows/Core validation.yml
Labels: enhancement

#56 Applying recommended community standards
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation, enhancement

#59 Publish `TryAtSoftware.Extensions.DependencyInjection`
  .github/workflows/Publish packages.yml
Labels: enhancement

#60 Fixed code smells
  TryAtSoftware.Extensions.Reflection.Tests/MemberInfoExtensionsTests.cs
  TryAtSoftware.Extensions.Reflection.Tests/TypeNamesTests.cs
Labels: enhancement

#61 Preparing the `TryAtSoftware.Extensions.DependencyInjection.Standard` package
  .github/workflows/Publish packages.yml
  README.md
  TryAtSoftware.Extensions.DependencyInjection.Standard.md
  TryAtSoftware.Extensions.DependencyInjection.Standard/TryAtSoftware.Extensions.DependencyInjection.Standard.csproj
  TryAtSoftware.Extensions.sln
Labels: documentation, enhancement, release

#65 Workflow optimizations for contributors (Uncertain changes)
  .github/workflows/Core validation.yml
Labels: enhancement, question

#62 Fixed a mistake in the documentation of `TryAtSoftware.Extensions.DependencyInjection.Standart`
  TryAtSoftware.Extensions.DependencyInjection.Standard.md
Labels: documentation, enhancement
